language: android

addons:
  sonarcloud:
    organization: "mgaetan89-github"

env:
  global:
    - ADB_INSTALL_TIMEOUT=10
    - ANDROID_BUILD_TOOLS=29.0.2
    - COMPILE_API_LEVEL=29

  matrix:
    - ANDROID_TARGET=25 ANDROID_ABI=armeabi-v7a ANDROID_TAG=google_apis

android:
  components:
    - tools
    - platform-tools

before_install:
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS"
  - yes | sdkmanager "platforms;android-$ANDROID_TARGET"
  - yes | sdkmanager "platforms;android-$COMPILE_API_LEVEL"
  - yes | sdkmanager "system-images;android-$ANDROID_TARGET;$ANDROID_TAG;$ANDROID_ABI"
  - sdkmanager --update
  - sdkmanager --list

before_script:
  - echo no | avdmanager create avd -f -n "test_$ANDROID_TARGET" -k "system-images;android-$ANDROID_TARGET;$ANDROID_TAG;$ANDROID_ABI"
  - $ANDROID_HOME/emulator/emulator-headless -memory 2048 -avd "test_$ANDROID_TARGET" -no-audio -no-window -no-snapshot &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - adb devices

script:
  - ./gradlew :MPChartLib:jacocoTestReport :MPChartLib:assembleAndroidTest :MPChartLib:connectedDebugAndroidTest :MPChartLib:createDebugCoverageReport sonarqube

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - adb logcat -d

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
