package com.github.mikephil.charting.utils

import android.graphics.RectF
import com.google.common.truth.Truth.assertThat
import org.junit.Before
import org.junit.Test

class ViewPortHandlerTest {
	private lateinit var viewPortHandler: ViewPortHandler

	@Before
	fun before() {
		this.viewPortHandler = ViewPortHandler()
	}

	@Test
	fun setChartDimens_biggestHeight() {
		this.viewPortHandler.setChartDimens(100f, 200f)

		assertThat(this.viewPortHandler.hasChartDimens()).isTrue()
		assertThat(this.viewPortHandler.offsetLeft()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetRight()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetTop()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetBottom()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentTop()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentLeft()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentRight()).isEqualTo(100f)
		assertThat(this.viewPortHandler.contentBottom()).isEqualTo(200f)
		assertThat(this.viewPortHandler.contentWidth()).isEqualTo(100f)
		assertThat(this.viewPortHandler.contentHeight()).isEqualTo(200f)
		assertThat(this.viewPortHandler.contentRect).isEqualTo(RectF(0f, 0f, 100f, 200f))
		assertThat(this.viewPortHandler.contentCenter).isEqualTo(MPPointF(50f, 100f))
		assertThat(this.viewPortHandler.chartHeight).isEqualTo(200f)
		assertThat(this.viewPortHandler.chartWidth).isEqualTo(100f)
		assertThat(this.viewPortHandler.smallestContentExtension).isEqualTo(100f)

		assertThat(this.viewPortHandler.isInBoundsLeft(-2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsLeft(-1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsRight(101f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsRight(102f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsX(-2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsX(-1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsX(101f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsX(102f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsTop(-1f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsTop(0f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsBottom(200f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsBottom(201f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsY(-1f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsY(0f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsY(200f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsY(201f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 0f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 200f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 201f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-1f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-1f, 0f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(-1f, 200f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(-1f, 201f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(101f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(101f, 0f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(101f, 200f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(101f, 201f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(102f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(102f, 0f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(102f, 200f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(102f, 201f)).isFalse()
	}

	@Test
	fun setChartDimens_biggestWidth() {
		this.viewPortHandler.setChartDimens(200f, 100f)

		assertThat(this.viewPortHandler.hasChartDimens()).isTrue()
		assertThat(this.viewPortHandler.offsetLeft()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetRight()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetTop()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetBottom()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentTop()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentLeft()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentRight()).isEqualTo(200f)
		assertThat(this.viewPortHandler.contentBottom()).isEqualTo(100f)
		assertThat(this.viewPortHandler.contentWidth()).isEqualTo(200f)
		assertThat(this.viewPortHandler.contentHeight()).isEqualTo(100f)
		assertThat(this.viewPortHandler.contentRect).isEqualTo(RectF(0f, 0f, 200f, 100f))
		assertThat(this.viewPortHandler.contentCenter).isEqualTo(MPPointF(100f, 50f))
		assertThat(this.viewPortHandler.chartHeight).isEqualTo(100f)
		assertThat(this.viewPortHandler.chartWidth).isEqualTo(200f)
		assertThat(this.viewPortHandler.smallestContentExtension).isEqualTo(100f)

		assertThat(this.viewPortHandler.isInBoundsLeft(-2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsLeft(-1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsRight(201f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsRight(202f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsX(-2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsX(-1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsX(201f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsX(202f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsTop(-1f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsTop(0f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsBottom(100f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsBottom(101f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsY(-1f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsY(0f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsY(100f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsY(101f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 0f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 100f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 101f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-1f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-1f, 0f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(-1f, 100f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(-1f, 101f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(201f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(201f, 0f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(201f, 100f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(201f, 101f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(202f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(202f, 0f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(202f, 100f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(202f, 101f)).isFalse()
	}

	@Test
	fun setChartDimens_empty() {
		this.viewPortHandler.setChartDimens(0f, 0f)

		assertThat(this.viewPortHandler.hasChartDimens()).isFalse()
		assertThat(this.viewPortHandler.offsetLeft()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetRight()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetTop()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetBottom()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentTop()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentLeft()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentRight()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentBottom()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentWidth()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentHeight()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentRect).isEqualTo(RectF(0f, 0f, 0f, 0f))
		assertThat(this.viewPortHandler.contentCenter).isEqualTo(MPPointF(0f, 0f))
		assertThat(this.viewPortHandler.chartHeight).isEqualTo(0f)
		assertThat(this.viewPortHandler.chartWidth).isEqualTo(0f)
		assertThat(this.viewPortHandler.smallestContentExtension).isEqualTo(0f)

		assertThat(this.viewPortHandler.isInBoundsLeft(-2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsLeft(-1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsRight(1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsRight(2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsX(-2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsX(-1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsX(1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsX(2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsTop(-1f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsTop(0f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsBottom(0f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsBottom(1f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsY(-1f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsY(0f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsY(1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 0f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-1f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-1f, 0f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(-1f, 1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(1f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(1f, 0f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(1f, 1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(2f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(2f, 0f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(2f, 1f)).isFalse()
	}

	@Test
	fun setChartDimens_heightOnly() {
		this.viewPortHandler.setChartDimens(0f, 200f)

		assertThat(this.viewPortHandler.hasChartDimens()).isFalse()
		assertThat(this.viewPortHandler.offsetLeft()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetRight()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetTop()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetBottom()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentTop()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentLeft()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentRight()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentBottom()).isEqualTo(200f)
		assertThat(this.viewPortHandler.contentWidth()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentHeight()).isEqualTo(200f)
		assertThat(this.viewPortHandler.contentRect).isEqualTo(RectF(0f, 0f, 0f, 200f))
		assertThat(this.viewPortHandler.contentCenter).isEqualTo(MPPointF(0f, 100f))
		assertThat(this.viewPortHandler.chartHeight).isEqualTo(200f)
		assertThat(this.viewPortHandler.chartWidth).isEqualTo(0f)
		assertThat(this.viewPortHandler.smallestContentExtension).isEqualTo(0f)

		assertThat(this.viewPortHandler.isInBoundsLeft(-2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsLeft(-1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsRight(1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsRight(2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsX(-2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsX(-1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsX(1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsX(2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsTop(-1f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsTop(0f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsBottom(200f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsBottom(201f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsY(-1f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsY(0f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsY(200f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsY(201f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 0f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 200f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 201f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-1f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-1f, 0f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(-1f, 200f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(-1f, 201f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(1f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(1f, 0f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(1f, 200f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(1f, 201f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(2f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(2f, 0f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(2f, 200f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(2f, 201f)).isFalse()
	}

	@Test
	fun setChartDimens_square() {
		this.viewPortHandler.setChartDimens(200f, 200f)

		assertThat(this.viewPortHandler.hasChartDimens()).isTrue()
		assertThat(this.viewPortHandler.offsetLeft()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetRight()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetTop()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetBottom()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentTop()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentLeft()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentRight()).isEqualTo(200f)
		assertThat(this.viewPortHandler.contentBottom()).isEqualTo(200f)
		assertThat(this.viewPortHandler.contentWidth()).isEqualTo(200f)
		assertThat(this.viewPortHandler.contentHeight()).isEqualTo(200f)
		assertThat(this.viewPortHandler.contentRect).isEqualTo(RectF(0f, 0f, 200f, 200f))
		assertThat(this.viewPortHandler.contentCenter).isEqualTo(MPPointF(100f, 100f))
		assertThat(this.viewPortHandler.chartHeight).isEqualTo(200f)
		assertThat(this.viewPortHandler.chartWidth).isEqualTo(200f)
		assertThat(this.viewPortHandler.smallestContentExtension).isEqualTo(200f)

		assertThat(this.viewPortHandler.isInBoundsLeft(-2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsLeft(-1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsRight(201f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsRight(202f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsX(-2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsX(-1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsX(201f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsX(202f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsTop(-1f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsTop(0f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsBottom(200f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsBottom(201f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsY(-1f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsY(0f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsY(200f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsY(201f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 0f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 200f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 201f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-1f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-1f, 0f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(-1f, 200f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(-1f, 201f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(201f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(201f, 0f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(201f, 200f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(201f, 201f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(202f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(202f, 0f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(202f, 200f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(202f, 201f)).isFalse()
	}

	@Test
	fun setChartDimens_widthOnly() {
		this.viewPortHandler.setChartDimens(200f, 0f)

		assertThat(this.viewPortHandler.hasChartDimens()).isFalse()
		assertThat(this.viewPortHandler.offsetLeft()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetRight()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetTop()).isEqualTo(0f)
		assertThat(this.viewPortHandler.offsetBottom()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentTop()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentLeft()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentRight()).isEqualTo(200f)
		assertThat(this.viewPortHandler.contentBottom()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentWidth()).isEqualTo(200f)
		assertThat(this.viewPortHandler.contentHeight()).isEqualTo(0f)
		assertThat(this.viewPortHandler.contentRect).isEqualTo(RectF(0f, 0f, 200f, 0f))
		assertThat(this.viewPortHandler.contentCenter).isEqualTo(MPPointF(100f, 0f))
		assertThat(this.viewPortHandler.chartHeight).isEqualTo(0f)
		assertThat(this.viewPortHandler.chartWidth).isEqualTo(200f)
		assertThat(this.viewPortHandler.smallestContentExtension).isEqualTo(0f)

		assertThat(this.viewPortHandler.isInBoundsLeft(-2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsLeft(-1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsRight(201f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsRight(202f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsX(-2f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsX(-1f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsX(201f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsX(202f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsTop(-1f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsTop(0f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsBottom(1f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsY(-1f)).isFalse()
		assertThat(this.viewPortHandler.isInBoundsY(0f)).isTrue()
		assertThat(this.viewPortHandler.isInBoundsY(1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 0f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-2f, 1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-1f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(-1f, 0f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(-1f, 1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(201f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(201f, 0f)).isTrue()
		assertThat(this.viewPortHandler.isInBounds(201f, 1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(202f, -1f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(202f, 0f)).isFalse()
		assertThat(this.viewPortHandler.isInBounds(202f, 1f)).isFalse()
	}

	@Test
	fun setMinimumScaleX() {
		assertThat(this.viewPortHandler.minScaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMinimumScaleX(10f)
		assertThat(this.viewPortHandler.minScaleX).isEqualTo(10f)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(10f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMinimumScaleX(0f)
		assertThat(this.viewPortHandler.minScaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(10f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)
	}

	@Test
	fun setMaximumScaleX() {
		assertThat(this.viewPortHandler.maxScaleX).isEqualTo(Float.MAX_VALUE)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMaximumScaleX(10f)
		assertThat(this.viewPortHandler.maxScaleX).isEqualTo(10f)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMaximumScaleX(0f)
		assertThat(this.viewPortHandler.maxScaleX).isEqualTo(Float.MAX_VALUE)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)
	}

	@Test
	fun setMinMaxScaleX() {
		assertThat(this.viewPortHandler.minScaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.maxScaleX).isEqualTo(Float.MAX_VALUE)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMinMaxScaleX(10f, 10f)
		assertThat(this.viewPortHandler.minScaleX).isEqualTo(10f)
		assertThat(this.viewPortHandler.maxScaleX).isEqualTo(10f)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(10f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMinMaxScaleX(10f, 0f)
		assertThat(this.viewPortHandler.minScaleX).isEqualTo(10f)
		assertThat(this.viewPortHandler.maxScaleX).isEqualTo(Float.MAX_VALUE)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(10f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMinMaxScaleX(0f, 10f)
		assertThat(this.viewPortHandler.minScaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.maxScaleX).isEqualTo(10f)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(10f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMinMaxScaleX(0f, 0f)
		assertThat(this.viewPortHandler.minScaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.maxScaleX).isEqualTo(Float.MAX_VALUE)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(10f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)
	}

	@Test
	fun setMinimumScaleY() {
		assertThat(this.viewPortHandler.minScaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMinimumScaleY(10f)
		assertThat(this.viewPortHandler.minScaleY).isEqualTo(10f)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(10f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMinimumScaleY(0f)
		assertThat(this.viewPortHandler.minScaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(10f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)
	}

	@Test
	fun setMaximumScaleY() {
		assertThat(this.viewPortHandler.maxScaleY).isEqualTo(Float.MAX_VALUE)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMaximumScaleY(10f)
		assertThat(this.viewPortHandler.maxScaleY).isEqualTo(10f)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMaximumScaleY(0f)
		assertThat(this.viewPortHandler.maxScaleY).isEqualTo(Float.MAX_VALUE)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)
	}

	@Test
	fun setMinMaxScaleY() {
		assertThat(this.viewPortHandler.minScaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.maxScaleY).isEqualTo(Float.MAX_VALUE)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMinMaxScaleY(10f, 10f)
		assertThat(this.viewPortHandler.minScaleY).isEqualTo(10f)
		assertThat(this.viewPortHandler.maxScaleY).isEqualTo(10f)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(10f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMinMaxScaleY(10f, 0f)
		assertThat(this.viewPortHandler.minScaleY).isEqualTo(10f)
		assertThat(this.viewPortHandler.maxScaleY).isEqualTo(Float.MAX_VALUE)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(10f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMinMaxScaleY(0f, 10f)
		assertThat(this.viewPortHandler.minScaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.maxScaleY).isEqualTo(10f)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(10f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)

		this.viewPortHandler.setMinMaxScaleY(0f, 0f)
		assertThat(this.viewPortHandler.minScaleY).isEqualTo(1f)
		assertThat(this.viewPortHandler.maxScaleY).isEqualTo(Float.MAX_VALUE)
		assertThat(this.viewPortHandler.scaleX).isEqualTo(1f)
		assertThat(this.viewPortHandler.scaleY).isEqualTo(10f)
		assertThat(this.viewPortHandler.transX).isEqualTo(0f)
		assertThat(this.viewPortHandler.transY).isEqualTo(0f)
	}
}
